### ISSUE TITLE
Preview image als er geen afbeelding beschikbaar

### ISSUE THREAD

**Issue by ghost** [nehlis/pr-ip-eenmaalandermaal#49]
![image](https://user-images.githubusercontent.com/6729273/101333240-aaeeb880-3876-11eb-9d8f-aa064aca4c28.png)

**Comment by thijmau** [comment]
Is geïmplementeerd

**Comment by SimonRijn** [comment]
Bij item 110960807154 is een foto beschikbaar

**Comment by SimonRijn** [comment]
Maak even een config file waarin je de path van een afbeelding aangeeft
