### ISSUE TITLE
Alle items in de database worden geladen zodra je op de veilingen pagina komt

### ISSUE THREAD

**Issue by SimonRijn** [nehlis/pr-ip-eenmaalandermaal#56]
Misschien iets van pagination? Even overleggen met Sander

**Comment by niels-bosman** [comment]
Dit is iets wat bij deze sprint hoort? Dan moeten we even snel zijn met het navragen aan @SanderLeer

**Comment by ghost** [comment]
Een fix hiervoor is al wip. Staat geplant voor sprint 3
