### ISSUE TITLE
Gesloten veilingen niet meer laten weergeven op de veilingpagina

### ISSUE THREAD

**Issue by SimonRijn** [nehlis/pr-ip-eenmaalandermaal#57]
Even met Sander overleggen wat hij wilt

![image](https://user-images.githubusercontent.com/20671637/101608167-aefd1080-3a05-11eb-802c-dd66e99215df.png)

**Comment by ghost** [comment]
In PHP is het al geregeld: 
![image](https://user-images.githubusercontent.com/6729273/101620174-82042a00-3a14-11eb-9cf5-16b35ad6b51b.png)

Moet even op SQL niveau instellen dat als de eindtijd voorbij is dat die flag op false gaat mbv DB triggers
