### ISSUE TITLE
Categorieën worden niet naar de DB gestuurd

### ISSUE THREAD

**Issue by SimonRijn** [nehlis/pr-ip-eenmaalandermaal#61]
Zodra er een item wordt aangemaakt worden de categorieën niet doorgestuurd naar de database waardoor hel hele script in de catch valt en het item ook niet meer word toegevoegd.

![image](https://user-images.githubusercontent.com/20671637/101762744-18e8e900-3ade-11eb-95b8-21a621f2aa71.png)

**Comment by ghost** [comment]
Zal er naar kijken, ligt aan de db wijziging inderdaad
