### ISSUE TITLE
Wanneer je een veiling toevoegd, komt er geen enddate en startdate bij te staan.

### ISSUE THREAD

**Issue by niels-bosman** [nehlis/pr-ip-eenmaalandermaal#91]
@ilivss dit is volgens mij in de code die jij geschreven hebt. In de master branch.

Hoe te reproduceren:
Ik voeg een auction toe (1 dag) -> unblock hem -> query op ID van de veiling om te zien dat hij een paar fields mist.

**Comment by ghost** [comment]
Dit was zo afgesproken. Volgens PO moest de start en einddatum bepaald worden wanneer de veiling "geactiveerd" wordt door de beheerder. 

Dus wanneer de beheerder de veiling "activeert" zullen deze ingevoerd moeten worden. Dit kan mbv database triggers of php

**Comment by niels-bosman** [comment]
> Dit was zo afgesproken. Volgens PO moest de start en einddatum bepaald worden wanneer de veiling "geactiveerd" wordt door de beheerder.
> 
> Dus wanneer de beheerder de veiling "activeert" zullen deze ingevoerd moeten worden. Dit kan mbv database triggers of php

Ik heb hem geactiveerd, maar dan zie ik hem nog steeds niet erbij staan, komt dit door de database trigger van @SimonRijn ?

**Comment by SimonRijn** [comment]
Ik heb helemaal niks gedaan met database triggers. Zal wel even kijken ernaar

**Comment by SimonRijn** [comment]
Fixed, PR incomming
